# Generated by Django 5.0.1 on 2025-05-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_comment_replies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_new_post_notifications',
        ),
    ]
