services:
  # A Django web service
  - type: web
    name: portfolio
    runtime: python
    buildCommand: ./build.sh
    startCommand: daphne PortfolioProject.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
