services:
  # A Django web service
  - type: web
    name: portfolio
    runtime: python
    buildCommand: ./build.sh
    startCommand: daphne PortfolioProject.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: SQLITE_PATH
        value: /opt/render/project/src/db/db.sqlite3
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/db
      sizeGB: 1
