# Generated by Django 5.0.1 on 2025-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', 'populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('Cloud Computing', 'Cloud Computing'), ('DevOps', 'DevOps'), ('Cybersecurity', 'Cybersecurity'), ('Blockchain', 'Blockchain'), ('IoT', 'Internet of Things'), ('Robotics', 'Robotics'), ('Software Engineering', 'Software Engineering'), ('UI/UX Design', 'UI/UX Design'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Database Systems', 'Database Systems'), ('Network Security', 'Network Security'), ('Game Development', 'Game Development'), ('Digital Marketing', 'Digital Marketing')], max_length=100),
        ),
    ]
