# Generated by Django 5.0.1 on 2025-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
