# Generated by Django 5.0.1 on 2025-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_blogpost_tags_blogpost_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Innovation', 'Innovation'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('AI & ML', 'AI & Machine Learning'), ('IoT', 'Internet of Things'), ('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Cloud Computing', 'Cloud Computing'), ('Cybersecurity', 'Cybersecurity'), ('Data Science', 'Data Science'), ('DevOps', 'DevOps')], max_length=100),
        ),
    ]
