# Generated by Django 5.0.1 on 2025-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether this post is publicly visible'),
        ),
    ]
