# Generated by Django 5.0.1 on 2025-05-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_content_project_features_project_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_screenshots/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('wide', 'Wide'), ('tall', 'Tall')], default='medium', help_text='Size in the bento grid layout', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='blog.project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ['order'],
            },
        ),
    ]
